# Generated by Django 5.2.5 on 2026-03-22 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(to='songs.genretag'),
        ),
        migrations.AddField(
            model_name='song',
            name='moods',
            field=models.ManyToManyField(to='songs.moodtag'),
        ),
        migrations.AddField(
            model_name='song',
            name='occasions',
            field=models.ManyToManyField(to='songs.occasiontag'),
        ),
    ]
