# Generated by Django 5.2.5 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="generation_task_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
