# Generated by Django 5.2.5 on 2026-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_generation_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
