# Generated by Django 5.2.5 on 2026-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_auth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
